const { NOTES, SHIFTS, INTERVALS, FULL_INTERVAL_QUALITY, DIRECTION } = require('../src/constants')

const { ASC, DSC } = DIRECTION
const { FLAT, NATURAL, SHARP } = SHIFTS
const { m, M, DISMINUIDA, JUSTA, AUMENTADA } = FULL_INTERVAL_QUALITY
const { II, III, IV, V, VI, VII } = INTERVALS

const ASC_TEST_CASES_D = [
  ['D', FLAT, II, m, ASC, 'Ebb'],
  ['D', FLAT, II, M, ASC, 'Eb'],
  ['D', FLAT, III, m, ASC, 'Fb'],
  ['D', FLAT, III, M, ASC, 'F'],
  ['D', FLAT, IV, DISMINUIDA, ASC, 'Gbb'],
  ['D', FLAT, IV, JUSTA, ASC, 'Gb'],
  ['D', FLAT, IV, AUMENTADA, ASC, 'G'],
  ['D', FLAT, V, DISMINUIDA, ASC, 'Abb'],
  ['D', FLAT, V, JUSTA, ASC, 'Ab'],
  ['D', FLAT, V, AUMENTADA, ASC, 'A'],
  ['D', FLAT, VI, m, ASC, 'Bbb'],
  ['D', FLAT, VI, M, ASC, 'Bb'],
  ['D', FLAT, VII, m, ASC, 'Cb'],
  ['D', FLAT, VII, M, ASC, 'C'],
  ['D', NATURAL, II, m, ASC, 'Eb'],
  ['D', NATURAL, II, M, ASC, 'E'],
  ['D', NATURAL, III, m, ASC, 'F'],
  ['D', NATURAL, III, M, ASC, 'F#'],
  ['D', NATURAL, IV, DISMINUIDA, ASC, 'Gb'],
  ['D', NATURAL, IV, JUSTA, ASC, 'G'],
  ['D', NATURAL, IV, AUMENTADA, ASC, 'G#'],
  ['D', NATURAL, V, DISMINUIDA, ASC, 'Ab'],
  ['D', NATURAL, V, JUSTA, ASC, 'A'],
  ['D', NATURAL, V, AUMENTADA, ASC, 'A#'],
  ['D', NATURAL, VI, m, ASC, 'Bb'],
  ['D', NATURAL, VI, M, ASC, 'B'],
  ['D', NATURAL, VII, m, ASC, 'C'],
  ['D', NATURAL, VII, M, ASC, 'C#'],
  ['D', SHARP, II, m, ASC, 'E'],
  ['D', SHARP, II, M, ASC, 'E#'],
  ['D', SHARP, III, m, ASC, 'F#'],
  ['D', SHARP, III, M, ASC, 'F##'],
  ['D', SHARP, IV, DISMINUIDA, ASC, 'G'],
  ['D', SHARP, IV, JUSTA, ASC, 'G#'],
  ['D', SHARP, IV, AUMENTADA, ASC, 'G##'],
  ['D', SHARP, V, DISMINUIDA, ASC, 'A'],
  ['D', SHARP, V, JUSTA, ASC, 'A#'],
  ['D', SHARP, V, AUMENTADA, ASC, 'A##'],
  ['D', SHARP, VI, m, ASC, 'B'],
  ['D', SHARP, VI, M, ASC, 'B#'],
  ['D', SHARP, VII, m, ASC, 'C#'],
  ['D', SHARP, VII, M, ASC, 'C##'],
]
const DSC_TEST_CASES_D = [
  ['D', FLAT, II, m, DSC, 'C'],
  ['D', FLAT, II, M, DSC, 'Cb'],
  ['D', FLAT, III, m, DSC, 'Bb'],
  ['D', FLAT, III, M, DSC, 'Bbb'],
  ['D', FLAT, IV, DISMINUIDA, DSC, 'A'],
  ['D', FLAT, IV, JUSTA, DSC, 'Ab'],
  ['D', FLAT, IV, AUMENTADA, DSC, 'Abb'],
  ['D', FLAT, V, DISMINUIDA, DSC, 'G'],
  ['D', FLAT, V, JUSTA, DSC, 'Gb'],
  ['D', FLAT, V, AUMENTADA, DSC, 'Gbb'],
  ['D', FLAT, VI, m, DSC, 'F'],
  ['D', FLAT, VI, M, DSC, 'Fb'],
  ['D', FLAT, VII, m, DSC, 'Eb'],
  ['D', FLAT, VII, M, DSC, 'Ebb'],
  ['D', NATURAL, II, m, DSC, 'C#'],
  ['D', NATURAL, II, M, DSC, 'C'],
  ['D', NATURAL, III, m, DSC, 'B'],
  ['D', NATURAL, III, M, DSC, 'Bb'],
  ['D', NATURAL, IV, DISMINUIDA, DSC, 'A#'],
  ['D', NATURAL, IV, JUSTA, DSC, 'A'],
  ['D', NATURAL, IV, AUMENTADA, DSC, 'Ab'],
  ['D', NATURAL, V, DISMINUIDA, DSC, 'G#'],
  ['D', NATURAL, V, JUSTA, DSC, 'G'],
  ['D', NATURAL, V, AUMENTADA, DSC, 'Gb'],
  ['D', NATURAL, VI, m, DSC, 'F#'],
  ['D', NATURAL, VI, M, DSC, 'F'],
  ['D', NATURAL, VII, m, DSC, 'E'],
  ['D', NATURAL, VII, M, DSC, 'Eb'],
  ['D', SHARP, II, m, DSC, 'C##'],
  ['D', SHARP, II, M, DSC, 'C#'],
  ['D', SHARP, III, m, DSC, 'B#'],
  ['D', SHARP, III, M, DSC, 'B'],
  ['D', SHARP, IV, DISMINUIDA, DSC, 'A##'],
  ['D', SHARP, IV, JUSTA, DSC, 'A#'],
  ['D', SHARP, IV, AUMENTADA, DSC, 'A'],
  ['D', SHARP, V, DISMINUIDA, DSC, 'G##'],
  ['D', SHARP, V, JUSTA, DSC, 'G#'],
  ['D', SHARP, V, AUMENTADA, DSC, 'G'],
  ['D', SHARP, VI, m, DSC, 'F##'],
  ['D', SHARP, VI, M, DSC, 'F#'],
  ['D', SHARP, VII, m, DSC, 'E#'],
  ['D', SHARP, VII, M, DSC, 'E'],
]
const ASC_TEST_CASES_E = [
  ['E', FLAT, II, m, ASC, 'Fb'],
  ['E', FLAT, II, M, ASC, 'F'],
  ['E', FLAT, III, m, ASC, 'Gb'],
  ['E', FLAT, III, M, ASC, 'G'],
  ['E', FLAT, IV, DISMINUIDA, ASC, 'Abb'],
  ['E', FLAT, IV, JUSTA, ASC, 'Ab'],
  ['E', FLAT, IV, AUMENTADA, ASC, 'A'],
  ['E', FLAT, V, DISMINUIDA, ASC, 'Bbb'],
  ['E', FLAT, V, JUSTA, ASC, 'Bb'],
  ['E', FLAT, V, AUMENTADA, ASC, 'B'],
  ['E', FLAT, VI, m, ASC, 'Cb'],
  ['E', FLAT, VI, M, ASC, 'C'],
  ['E', FLAT, VII, m, ASC, 'Db'],
  ['E', FLAT, VII, M, ASC, 'D'],
  ['E', NATURAL, II, m, ASC, 'F'],
  ['E', NATURAL, II, M, ASC, 'F#'],
  ['E', NATURAL, III, m, ASC, 'G'],
  ['E', NATURAL, III, M, ASC, 'G#'],
  ['E', NATURAL, IV, DISMINUIDA, ASC, 'Ab'],
  ['E', NATURAL, IV, JUSTA, ASC, 'A'],
  ['E', NATURAL, IV, AUMENTADA, ASC, 'A#'],
  ['E', NATURAL, V, DISMINUIDA, ASC, 'Bb'],
  ['E', NATURAL, V, JUSTA, ASC, 'B'],
  ['E', NATURAL, V, AUMENTADA, ASC, 'B#'],
  ['E', NATURAL, VI, m, ASC, 'C'],
  ['E', NATURAL, VI, M, ASC, 'C#'],
  ['E', NATURAL, VII, m, ASC, 'D'],
  ['E', NATURAL, VII, M, ASC, 'D#'],
  ['E', SHARP, II, m, ASC, 'F#'],
  ['E', SHARP, II, M, ASC, 'F##'],
  ['E', SHARP, III, m, ASC, 'G#'],
  ['E', SHARP, III, M, ASC, 'G##'],
  ['E', SHARP, IV, DISMINUIDA, ASC, 'A'],
  ['E', SHARP, IV, JUSTA, ASC, 'A#'],
  ['E', SHARP, IV, AUMENTADA, ASC, 'A##'],
  ['E', SHARP, V, DISMINUIDA, ASC, 'B'],
  ['E', SHARP, V, JUSTA, ASC, 'B#'],
  ['E', SHARP, V, AUMENTADA, ASC, 'B##'],
  ['E', SHARP, VI, m, ASC, 'C#'],
  ['E', SHARP, VI, M, ASC, 'C##'],
  ['E', SHARP, VII, m, ASC, 'D#'],
  ['E', SHARP, VII, M, ASC, 'D##'],
]
const DSC_TEST_CASES_E = [
  ['E', FLAT, II, m, DSC, 'D'],
  ['E', FLAT, II, M, DSC, 'Db'],
  ['E', FLAT, III, m, DSC, 'C'],
  ['E', FLAT, III, M, DSC, 'Cb'],
  ['E', FLAT, IV, DISMINUIDA, DSC, 'B'],
  ['E', FLAT, IV, JUSTA, DSC, 'Bb'],
  ['E', FLAT, IV, AUMENTADA, DSC, 'Bbb'],
  ['E', FLAT, V, DISMINUIDA, DSC, 'A'],
  ['E', FLAT, V, JUSTA, DSC, 'Ab'],
  ['E', FLAT, V, AUMENTADA, DSC, 'Abb'],
  ['E', FLAT, VI, m, DSC, 'G'],
  ['E', FLAT, VI, M, DSC, 'Gb'],
  ['E', FLAT, VII, m, DSC, 'F'],
  ['E', FLAT, VII, M, DSC, 'Fb'],
  ['E', NATURAL, II, m, DSC, 'D#'],
  ['E', NATURAL, II, M, DSC, 'D'],
  ['E', NATURAL, III, m, DSC, 'C#'],
  ['E', NATURAL, III, M, DSC, 'C'],
  ['E', NATURAL, IV, DISMINUIDA, DSC, 'B#'],
  ['E', NATURAL, IV, JUSTA, DSC, 'B'],
  ['E', NATURAL, IV, AUMENTADA, DSC, 'Bb'],
  ['E', NATURAL, V, DISMINUIDA, DSC, 'A#'],
  ['E', NATURAL, V, JUSTA, DSC, 'A'],
  ['E', NATURAL, V, AUMENTADA, DSC, 'Ab'],
  ['E', NATURAL, VI, m, DSC, 'G#'],
  ['E', NATURAL, VI, M, DSC, 'G'],
  ['E', NATURAL, VII, m, DSC, 'F#'],
  ['E', NATURAL, VII, M, DSC, 'F'],
  ['E', SHARP, II, m, DSC, 'D##'],
  ['E', SHARP, II, M, DSC, 'D#'],
  ['E', SHARP, III, m, DSC, 'C##'],
  ['E', SHARP, III, M, DSC, 'C#'],
  ['E', SHARP, IV, DISMINUIDA, DSC, 'B##'],
  ['E', SHARP, IV, JUSTA, DSC, 'B#'],
  ['E', SHARP, IV, AUMENTADA, DSC, 'B'],
  ['E', SHARP, V, DISMINUIDA, DSC, 'A##'],
  ['E', SHARP, V, JUSTA, DSC, 'A#'],
  ['E', SHARP, V, AUMENTADA, DSC, 'A'],
  ['E', SHARP, VI, m, DSC, 'G##'],
  ['E', SHARP, VI, M, DSC, 'G#'],
  ['E', SHARP, VII, m, DSC, 'F##'],
  ['E', SHARP, VII, M, DSC, 'F#'],
]
const ASC_TEST_CASES_B = [
  ['B', FLAT, II, m, ASC, 'Cb'],
  ['B', FLAT, II, M, ASC, 'C'],
  ['B', FLAT, III, m, ASC, 'Db'],
  ['B', FLAT, III, M, ASC, 'D'],
  ['B', FLAT, IV, DISMINUIDA, ASC, 'Ebb'],
  ['B', FLAT, IV, JUSTA, ASC, 'Eb'],
  ['B', FLAT, IV, AUMENTADA, ASC, 'E'],
  ['B', FLAT, V, DISMINUIDA, ASC, 'Fb'],
  ['B', FLAT, V, JUSTA, ASC, 'F'],
  ['B', FLAT, V, AUMENTADA, ASC, 'F#'],
  ['B', FLAT, VI, m, ASC, 'Gb'],
  ['B', FLAT, VI, M, ASC, 'G'],
  ['B', FLAT, VII, m, ASC, 'Ab'],
  ['B', FLAT, VII, M, ASC, 'A'],
  ['B', NATURAL, II, m, ASC, 'C'],
  ['B', NATURAL, II, M, ASC, 'C#'],
  ['B', NATURAL, III, m, ASC, 'D'],
  ['B', NATURAL, III, M, ASC, 'D#'],
  ['B', NATURAL, IV, DISMINUIDA, ASC, 'Eb'],
  ['B', NATURAL, IV, JUSTA, ASC, 'E'],
  ['B', NATURAL, IV, AUMENTADA, ASC, 'E#'],
  ['B', NATURAL, V, DISMINUIDA, ASC, 'F'],
  ['B', NATURAL, V, JUSTA, ASC, 'F#'],
  ['B', NATURAL, V, AUMENTADA, ASC, 'F##'],
  ['B', NATURAL, VI, m, ASC, 'G'],
  ['B', NATURAL, VI, M, ASC, 'G#'],
  ['B', NATURAL, VII, m, ASC, 'A'],
  ['B', NATURAL, VII, M, ASC, 'A#'],
  ['B', SHARP, II, m, ASC, 'C#'],
  ['B', SHARP, II, M, ASC, 'C##'],
  ['B', SHARP, III, m, ASC, 'D#'],
  ['B', SHARP, III, M, ASC, 'D##'],
  ['B', SHARP, IV, DISMINUIDA, ASC, 'E'],
  ['B', SHARP, IV, JUSTA, ASC, 'E#'],
  ['B', SHARP, IV, AUMENTADA, ASC, 'E##'],
  ['B', SHARP, V, DISMINUIDA, ASC, 'F#'],
  ['B', SHARP, V, JUSTA, ASC, 'F##'],
  ['B', SHARP, V, AUMENTADA, ASC, 'F###'],
  ['B', SHARP, VI, m, ASC, 'G#'],
  ['B', SHARP, VI, M, ASC, 'G##'],
  ['B', SHARP, VII, m, ASC, 'A#'],
  ['B', SHARP, VII, M, ASC, 'A##'],
]
const DSC_TEST_CASES_B = [
  ['B', FLAT, II, m, DSC, 'A'],
  ['B', FLAT, II, M, DSC, 'Ab'],
  ['B', FLAT, III, m, DSC, 'G'],
  ['B', FLAT, III, M, DSC, 'Gb'],
  ['B', FLAT, IV, DISMINUIDA, DSC, 'F#'],
  ['B', FLAT, IV, JUSTA, DSC, 'F'],
  ['B', FLAT, IV, AUMENTADA, DSC, 'Fb'],
  ['B', FLAT, V, DISMINUIDA, DSC, 'E'],
  ['B', FLAT, V, JUSTA, DSC, 'Eb'],
  ['B', FLAT, V, AUMENTADA, DSC, 'Ebb'],
  ['B', FLAT, VI, m, DSC, 'D'],
  ['B', FLAT, VI, M, DSC, 'Db'],
  ['B', FLAT, VII, m, DSC, 'C'],
  ['B', FLAT, VII, M, DSC, 'Cb'],
  ['B', NATURAL, II, m, DSC, 'A#'],
  ['B', NATURAL, II, M, DSC, 'A'],
  ['B', NATURAL, III, m, DSC, 'G#'],
  ['B', NATURAL, III, M, DSC, 'G'],
  ['B', NATURAL, IV, DISMINUIDA, DSC, 'F##'],
  ['B', NATURAL, IV, JUSTA, DSC, 'F#'],
  ['B', NATURAL, IV, AUMENTADA, DSC, 'F'],
  ['B', NATURAL, V, DISMINUIDA, DSC, 'E#'],
  ['B', NATURAL, V, JUSTA, DSC, 'E'],
  ['B', NATURAL, V, AUMENTADA, DSC, 'Eb'],
  ['B', NATURAL, VI, m, DSC, 'D#'],
  ['B', NATURAL, VI, M, DSC, 'D'],
  ['B', NATURAL, VII, m, DSC, 'C#'],
  ['B', NATURAL, VII, M, DSC, 'C'],
  ['B', SHARP, II, m, DSC, 'A##'],
  ['B', SHARP, II, M, DSC, 'A#'],
  ['B', SHARP, III, m, DSC, 'G##'],
  ['B', SHARP, III, M, DSC, 'G#'],
  ['B', SHARP, IV, DISMINUIDA, DSC, 'F###'],
  ['B', SHARP, IV, JUSTA, DSC, 'F##'],
  ['B', SHARP, IV, AUMENTADA, DSC, 'F#'],
  ['B', SHARP, V, DISMINUIDA, DSC, 'E##'],
  ['B', SHARP, V, JUSTA, DSC, 'E#'],
  ['B', SHARP, V, AUMENTADA, DSC, 'E'],
  ['B', SHARP, VI, m, DSC, 'D##'],
  ['B', SHARP, VI, M, DSC, 'D#'],
  ['B', SHARP, VII, m, DSC, 'C##'],
  ['B', SHARP, VII, M, DSC, 'C#'],
]

const NEW_TEST_CASES = [
  ...ASC_TEST_CASES_D,
  ...DSC_TEST_CASES_D,
  ...ASC_TEST_CASES_E,
  ...DSC_TEST_CASES_E,
  ...ASC_TEST_CASES_B,
  ...DSC_TEST_CASES_B,
]

module.exports = {
  NEW_TEST_CASES,
}
